# Generated by Django 3.0.6 on 2020-05-07 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todowoorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(max_length=120)),
                ('date', models.DateField(default=datetime.date(2020, 5, 7))),
                ('status', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appusers.Allusers')),
            ],
        ),
    ]
