# Generated by Django 3.0.6 on 2020-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todowoorks',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
