# Generated by Django 3.0.6 on 2020-05-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200508_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='todowoorks',
            name='fileupload',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
